### ISSUE TITLE
Migrate all partner charts out of our repos and clean up

### ISSUE THREAD

**Issue by pennyscissors** [rancher/tasks#168]
Investigate how we can migrate all partner charts from our repositories into their own to simplify the submission process for them, and restructure our repositories/branching post migration.

Some important details to investigate:
* Are there any partner that aren't active anymore and therefore their charts can be removed to make the migration easier?
* How will migrating partner charts currently in `rancher/charts` and `rancher/helm3-charts` impact users?
* How can we restructure the partner chart repos? Would it be better to have 3 separate repos, one for helm2 partner charts, another for helm3 and rancher/partner-charts, or have all partner charts in `rancher/partner-charts` and separate by branches (feature-charts, helm2-charts, helm3-charts, or something like that)?
* How can we restructure our repos post partner chart migration? Can we rename the master branch in `rancher/charts` to `legacy-charts` and have feature charts as the default? Would it be better to migrate feature charts into a new `rancher/feature-charts` repo, get rid of `rancher/helm3-charts` and use `rancher/charts` as our legacy charts repo with branches for each helm version?

**Comment by aiyengar2** [comment]
#### re: migrating all partner charts from our repositories into their own to simplify the submission process for them

The new scripts should allow us to declare Source branches in partner-owned repositories that validate against a Staging branch in our Rancher repository. 

But based on recent conversation offline with @PennyScissors I think this is something we want to avoid since this makes reviewing partner-chart PRs and keeping them up to date with script versions / docs difficult to do.

#### re: migrating already-released repos / renaming branches, like rancher/charts & rancher/helm3-charts

I don't think this is something we can do since older Rancher releases still point to the older repo / naming schemes, so we can only create net-new branches and repositories that are referred to from now onwards.

So migrating partner-charts currently in rancher/charts and rancher/helm3-charts would mostly be copying them to a new repository / branch that would maintain them.

**Comment by pennyscissors** [comment]
Closing because the plans for partner charts have changed due to a different team potentially taking over the projects.
